-- 플랫폼 배경색, 글자색 추가
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_BG_COLOR = '#088F8F' WHERE ROWID = 'AAAFKgAABAAALSRAAA' AND ORA_ROWSCN = '1083260'
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_BG_COLOR = '#f9e000', PLATFORM_FONT_COLOR = '#333' WHERE ROWID = 'AAAFKgAABAAALSRAAB' AND ORA_ROWSCN = '1083260'
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_BG_COLOR = '#03c75a', PLATFORM_FONT_COLOR = '#000' WHERE ROWID = 'AAAFKgAABAAALSRAAC' AND ORA_ROWSCN = '1083260'
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_BG_COLOR = '#1E9EFF' WHERE ROWID = 'AAAFKgAABAAALSRAAD' AND ORA_ROWSCN = '1083260'
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_NAME = '카카오웹툰', PLATFORM_BG_COLOR = '#000' WHERE ROWID = 'AAAFKgAABAAALSRAAE' AND ORA_ROWSCN = '1083260'
UPDATE "IBINI"."PRJ_PLATFORM" SET PLATFORM_BG_COLOR = '#03c75a', PLATFORM_FONT_COLOR = '#fff' WHERE ROWID = 'AAAFKgAABAAALSRAAF' AND ORA_ROWSCN = '1083260'
--0 미분류          배경: #088F8F 글자색: #fff
--1 카카오 페이지   배경: #f9e000	글자색: #333
--2 네이버 시리즈   배경: #03c75a	글자색: #000
--3 리디북스        배경: #1E9EFF	글자색: #fff
--4 카카오 웹툰     배경: #000	    글자색: #fff
--5 네이버 퉵툰   배경: #03c75a	글자색: #fff
--문피아          배경: #5aa2dd/ #5f9bd1 글자색: #333
--조아라          배경: #004c99 글자색: #a5f72c